config/routes.rb
AlwaysInMyMemory::Application.routes.draw do


  resources :cards,:users, :sessions
  root to: "cards#index", as: :home

  get '/signup' => 'users#new'
  get '/signout', to: 'sessions#destroy', via: :delete
  get'/signin', to: 'sessions#new'


  get "/users/:id/cards/show", to: 'cards#show', as: :show
  get "/users/:id/practice", to: 'cards#practice', as: :practice
  get "/users/:id/learned", to: 'cards#learned', as: :learned
  
   get "/users/:id/reserve", to: 'cards#reserve', as: :reserve
   post "users/:id/reserve", to: 'cards#create'

   post "/practice", to: "cards#viewed_stack"

   

 end


  

app/views/layouts/_header.html.erb
<nav class="navbar navbar-fixed-top navbar-inverse" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" id="brand" href="/"><strong>Forget Me Not</strong></a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to("Practice", practice_path(current_user.id), :class => "active") %></li>
        <li><%= link_to('Add cards', reserve_path(current_user.id)) %></li>
        <li><%= link_to('I know it', learned_path(current_user.id))%></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if signed_in? %>
          <li><%= link_to current_user.name, current_user %></li>
          <li><%= link_to "Sign out", signout_path, method: "delete" %></li>
        <% else %>
         <li><%= link_to "Sign up", signup_path %></li>
         <li><%= link_to "Sign in", signin_path %><li>
       <% end %>
     </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
    <title>forget me not</title>
 
     <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>

   <!-- App-like mobile view -->
                 <meta name="viewport" content="width=device-width, initial-scale=1.0, height=device-height, user-scalable=no"/>
                 
                <!-- Jquery -->
                <script src="http://code.jquery.com/jquery-2.1.0.min.js"></script>

                 <!-- Normalize -->
                 <link rel="stylesheet" src="//normalize-css.googlecode.com/svn/trunk/normalize.css" />
 
                 <!-- Boostrap core CSS -->
                 <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css" type="text/css">

               <!--   Link to googlefont -->
                 <link href='http://fonts.googleapis.com/css?family=Artifika' rel='stylesheet' type='text/css'>

                 <!-- Bootstrap styling CSS -->
                 <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap-theme.min.css" type="text/css">

                <!-- Bootstrap JS -->
                <script src="//netdna.bootstrapcdn.com/bootstrap/3.0.0/js/bootstrap.min.js"></script>
 
                <%= include_gon %>

                <%= javascript_include_tag "application" %>
                
                <%= csrf_meta_tags %>
    <!-- 
    <link rel="shortcut icon" href="../../docs-assets/ico/favicon.png">
    <link href='http://fonts.googleapis.com/css?family=Overlock|Offside|Supermercado+One|Medula+One|Aubrey' rel='stylesheet' type='text/css'> -->

</head>
<body>


<%= yield %>


</body>
</html>